packages:brokers:
  - '### Which package is this bug report for\?\n\nbrokers'
packages:builders:
  - '### Which package is this bug report for\?\n\nbuilders'
packages:collection:
  - '### Which package is this bug report for\?\n\ncollection'
packages:discord.js:
  - '### Which package is this bug report for\?\n\ndiscord.js'
packages:rest:
  - '### Which package is this bug report for\?\n\nrest'
packages/proxy:
  - '### Which package is this bug report for\?\n\nproxy'
packages:proxy-container:
  - '### Which package is this bug report for\?\n\nproxy-container'
packages:voice:
  - '### Which package is this bug report for\?\n\nvoice'
packages:ws:
  - '### Which package is this bug report for\?\n\nws'
